# Generated by Django 2.1 on 2018-10-16 23:00

import appMyZak.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', appMyZak.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id_banque', models.AutoField(primary_key=True, serialize=False)),
                ('nom_banque', models.CharField(max_length=50)),
                ('wb_banque', models.CharField(max_length=500)),
                ('wb_website', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id_compteBancaire', models.AutoField(primary_key=True, serialize=False)),
                ('login_compteBancaire', models.CharField(max_length=50)),
                ('password_compteBancaire', models.CharField(max_length=50)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMyZak.Banque')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('numero', models.IntegerField()),
                ('nom_departement', models.CharField(max_length=50)),
                ('dep_ip', models.AutoField(primary_key=True, serialize=False)),
                ('mon_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id_historique', models.AutoField(primary_key=True, serialize=False)),
                ('blocs', jsonfield.fields.JSONField(default='{"blocs":[{"ID":0,"nature":"init","date":"","solde_banque":0,"solde_espece":0,"solde_immo":0,"etat":"disabled"}]}')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id_situation', models.AutoField(primary_key=True, serialize=False)),
                ('date_situation', models.DateTimeField()),
                ('solde_banque', models.IntegerField()),
                ('solde_espece', models.IntegerField()),
                ('isImposable_or', models.BooleanField()),
                ('isImposable_argent', models.BooleanField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
