# Generated by Django 2.0.6 on 2018-06-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom_departement', models.CharField(max_length=50)),
                ('dep_ip', models.IntegerField()),
            ],
        ),
    ]
