# Generated by Django 2.0.6 on 2018-06-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='id',
        ),
        migrations.AlterField(
            model_name='departement',
            name='dep_ip',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
