# Generated by Django 2.0.6 on 2018-07-19 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_banque_comptebancaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id_situation', models.AutoField(primary_key=True, serialize=False)),
                ('date_situation', models.DateTimeField()),
                ('solde_banque', models.IntegerField()),
                ('solde_espece', models.IntegerField()),
                ('isImposable_or', models.BooleanField()),
                ('isImposable_argent', models.BooleanField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
