# Generated by Django 2.1 on 2018-09-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_historique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banque',
            old_name='urlHome_banque',
            new_name='wb_banque',
        ),
        migrations.RenameField(
            model_name='banque',
            old_name='urlLogin_banque',
            new_name='wb_website',
        ),
    ]
